# Generated by Django 5.0.3 on 2025-06-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_rename_tast_type_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
