# Generated by Django 5.0.3 on 2025-06-20 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_submission_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='score',
            new_name='marks_awarded',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='answer',
            new_name='submitted_answer',
        ),
        migrations.RemoveField(
            model_name='task',
            name='expected_output',
        ),
        migrations.AddField(
            model_name='submission',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('oneword', 'One Word Answer'), ('code', 'Coding'), ('upload', 'File Upload')], max_length=20),
        ),
    ]
